# Jekyll configuration

name: STEM Summer Camp - Data Science Track
description: Welcome to the Data Science page for the STEM Summer Camp
locale: en_US

# url is currently only used only for the RSS feed in feed.xml
url: https://custemcamp.org

# Used internally to switch between Chinese and English
# We just need English
lan: en

## default date_format
#date_format: 
#  title: "%B-%-d-%Y"
#  archive: "%b"
#  categories: "%b-%Y"
#  tag: "%b-%Y"
# Language
lan: "en" 

paginate: 10

highlighter: rouge
markdown: kramdown
plugins: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE', "*.bak", "vendor"]
